# Generated by Django 4.1.5 on 2023-02-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Can publish product'), ('change_description', 'Can change product description'), ('change_category', 'Can change product category')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
